export const REGISTER_USER = "REGISTER_USER";
export const FETCH_REGISTER_STARTED = "FETCH_REGISTER_STARTED";
export const FETCH_REGISTER_SUCCES = "FETCH_REGISTER_SUCCES";
export const FETCH_REGISTER_ERROR = "FETCH_REGISTER_ERROR";

/* export const DELETE_USER = "DELETE_USER";
export const EDIT_USER = "EDIT_USER"; */
