export const ADD_TODOS_STARTED = "ADD_TODOS_STARTED";
export const ADD_TODOS_SUCCESS = "ADD_TODOS_SUCCESS";

export const LIST_TODOS_STARTED = "LIST_TODOS_STARTED";
export const LIST_TODOS_SUCCESS = "LIST_TODOS_SUCCESS";

export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";

export const UPDATE_TODO_SUCCESS = "UPDATE_TODO_SUCCESS";
