export const USER_REGISTER_STARTED = "USER_REGISTER_STARTED";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_ERROR = "USER_REGISTER_ERROR";

/* export const LOGIN_USER = "LOGIN_USER_STRATED";
export const LOGIN_USER = "LOGIN_USER_SUCCESS";
export const LOGIN_USER = "LOGIN_USER_ERROR";
 */
